app/controllers/issues_controller.py
"""issues_controller.py
"""
import os
import logging
import requests
from flask import session
from requests.exceptions import RequestException
from app.controllers.auth_controller import get_installation_access_token

def get_github_issues(repo_name):
    """Fetches GitHub issues within a repository."""
    
    username = session.get('github_username') 
    access_token = get_installation_access_token()

    if not access_token:
        logging.error("Access token is missing. Cannot fetch GitHub issues.")
        return None

    url = f'https://api.github.com/repos/{username}/{repo_name}/issues'
    headers = {'Authorization': f'Bearer {access_token}'}

    try:
        response = requests.get(url, headers=headers, timeout=60)
        response.raise_for_status()
        issues = response.json()
        logging.info(f"Fetched {len(issues)} issues for repository {repo_name}.")
        return issues
    except RequestException as e:
        logging.error(f"Failed to fetch issues for repository {repo_name}: {e}")
        return None

def create_github_issue(repo_name, title, body=None):
    """Creates a new GitHub issue."""
    username = session.get('github_username')  
    access_token = get_installation_access_token()

    if not access_token:
        logging.error("Access token is missing. Cannot create GitHub issues.")
        return None

    url = f'https://api.github.com/repos/{username}/{repo_name}/issues'
    headers = {'Authorization': f'Bearer {access_token}'}
    data = {"title": title, "body": body}

    try:
        response = requests.post(url, json=data, headers=headers, timeout=60)
        response.raise_for_status()
        issue = response.json()
        logging.info(f"Issue created successfully in repository {repo_name}.")
        return issue
    except RequestException as e:
        logging.error(f"Failed to create issue in repository {repo_name}: {e}")
        return None

def close_github_issue(repo_name, issue_number):
    """Closes an existing GitHub issue."""
    username = session.get('github_username')
    access_token = get_installation_access_token()

    if not access_token:
        logging.error("Access token is missing. Cannot close GitHub issues.")
        return None

    url = f'https://api.github.com/repos/{username}/{repo_name}/issues/{issue_number}'
    headers = {'Authorization': f'Bearer {access_token}'}
    data = {"state": "closed"}

    try:
        response = requests.patch(url, json=data, headers=headers, timeout=60)
        response.raise_for_status()
        closed_issue = response.json()
        logging.info(f"Issue #{issue_number} successfully closed in repository {repo_name}.")
        return closed_issue
    except RequestException as e:
        logging.error(f"Failed to close issue #{issue_number} in repository {repo_name}: {e}")
        return None

app/controllers/pull_requests_controller.py
"""pull_requests_controller.py
"""
import logging
import requests
from requests.exceptions import RequestException
from app.controllers.auth_controller import get_installation_access_token

def get_pull_requests(owner, repo_name):
    """Lists all pull requests for a repository."""
    access_token = get_installation_access_token()

    if not access_token:
        logging.error("Access token is missing. Cannot fetch pull requests.")
        return None

    headers = {'Authorization': f'Bearer {access_token}'}
    api_url = f'https://api.github.com/repos/{owner}/{repo_name}/pulls'

    try:
        response = requests.get(api_url, headers=headers, timeout=60)
        response.raise_for_status()

        pulls = response.json()
        logging.info(f"Fetched {len(pulls)} pull requests for repository {repo_name}.")
        return pulls
    except RequestException as e:
        logging.error(f"Failed to fetch pull requests for repository {repo_name}: {e}")
        return None

def view_pull_request(owner, repo_name, pr_number):
    """Fetches details for a GitHub pull request."""
    access_token = get_installation_access_token()

    if not access_token:
        logging.error("Access token is missing. Cannot fetch pull request details.")
        return None

    headers = {'Authorization': f'Bearer {access_token}'}
    api_url = f'https://api.github.com/repos/{owner}/{repo_name}/pulls/{pr_number}'

    try:
        response = requests.get(api_url, headers=headers, timeout=60)
        response.raise_for_status()

        pull = response.json()
        logging.info(f"Fetched pull request #{pr_number} for repository {repo_name}.")
        return pull
    except RequestException as e:
        logging.error(f"Failed to fetch pull request details: {e}")
        return None

def create_pull_request(owner, repo_name, title, body, base, head):
    """Creates a new GitHub pull request."""
    access_token = get_installation_access_token()

    if not access_token:
        logging.error("Access token is missing. Cannot create pull request.")
        return None

    headers = {'Authorization': f'Bearer {access_token}'}
    payload = {'title': title, 'body': body, 'base': base, 'head': head}
    api_url = f'https://api.github.com/repos/{owner}/{repo_name}/pulls'

    logging.debug(f"Payload for creating PR: {payload}")

    try:
        response = requests.post(api_url, headers=headers, json=payload, timeout=60)
        response.raise_for_status()

        pull = response.json()
        logging.info(f"Pull request created successfully in repository {repo_name}.")
        return pull
    except requests.exceptions.RequestException as e:
        if e.response:
            logging.error(f"Failed to create pull request: {e.response.json()}")
        else:
            logging.error(f"Failed to create pull request: {e}")
        return None

def merge_pull_request(owner, repo_name, pr_number):
    """Merges a pull request in a repository."""
    access_token = get_installation_access_token()

    if not access_token:
        logging.error("Access token is missing. Cannot merge pull request.")
        return None

    headers = {'Authorization': f'Bearer {access_token}'}
    api_url = f'https://api.github.com/repos/{owner}/{repo_name}/pulls/{pr_number}/merge'

    try:
        response = requests.put(api_url, headers=headers, timeout=60)
        if response.status_code == 409:
            logging.error(f"Merge conflict for pull request #{pr_number} in repository {repo_name}.")
            return {"error": "Merge conflict"}

        response.raise_for_status()
        merge_result = response.json()
        logging.info(f"Pull request #{pr_number} successfully merged in repository {repo_name}.")
        return merge_result
    except RequestException as e:
        logging.error(f"Failed to merge pull request #{pr_number}: {e}")
        return None

app/routes/main_routes.py
"""main_routes.py
"""
import os
import logging
import requests
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from app.controllers.auth_controller import get_installation_access_token, is_user_logged_in, get_jwt, clear_session
from app.controllers.issues_controller import get_github_issues, create_github_issue, close_github_issue
from app.controllers.repo_controller import get_github_repositories, delete_repository, get_branches, get_branch_details, create_branch, get_default_branch_sha, get_repository_contents, create_file, update_file, delete_file
from app.controllers.pull_requests_controller import get_pull_requests, create_pull_request, merge_pull_request, view_pull_request

main_routes = Blueprint('main', __name__)

@main_routes.route('/')
def home():
    """
    Renders the home page.
    """
    return render_template('index.html', is_user_logged_in=is_user_logged_in)

@main_routes.route('/logout')
def logout():
    """
    Route to log out the user.
    """
    clear_session()
    flash("You have been logged out successfully.", "info")
    return redirect(url_for('main.home'))

@main_routes.route('/github/authorize', methods=['GET'])
def github_authorize():
    """
    Handle the GitHub App installation callback.
    """
    installation_id = request.args.get('installation_id')

    if not installation_id:
        logging.error("No installation ID provided in the request.")
        return "Installation ID is missing. Please install the GitHub App again.", 400

    session['installation_id'] = installation_id
    logging.info(f"Received installation ID: {installation_id}")

    access_token = get_installation_access_token()
    if access_token:
        logging.info("Installation access token successfully generated.")
        return redirect(url_for('main.home'))
    else:
        logging.error("Failed to generate installation access token.")
        return "Failed to complete installation process. Please try again.", 500

@main_routes.route('/github/install', methods=['GET'])
def install_github_app():
    """
    Redirect the user to the GitHub App installation page.
    """
    github_app_name = os.getenv("GITHUB_APP_NAME")  
    if not github_app_name:
        logging.error("GITHUB_APP_ID is not set in the environment.")
        return "Configuration error: GITHUB_APP_ID is not defined.", 500

    installation_url = f"https://github.com/apps/{github_app_name}/installations/new"
    return redirect(installation_url)

@main_routes.route('/github/repositories')
def show_github_repositories():
    """
    Display user's GitHub repositories.
    """
    if not is_user_logged_in():
        logging.warning("User attempted to access repositories without being logged in.")
        return "You are not logged in", 403

    username = session['github_username']  
    access_token = get_installation_access_token()

    if access_token:
        repositories = get_github_repositories(username, access_token)
        if repositories:
            logging.info(f"Fetched repositories for user: {username}, count: {len(repositories)}")
            return render_template('repositories.html', repositories=repositories)
        else:
            logging.error(f"Failed to fetch repositories for user: {username}")
            return "Failed to fetch repositories from GitHub", 500
    else:
        logging.error("Failed to get access token for GitHub repositories.")
        return "Failed to authenticate with GitHub", 500

@main_routes.route('/github/repository/<owner>/<repo_name>')
def show_repo_details(owner, repo_name):
    """
    Display repository details, including branches.
    """
    access_token = get_installation_access_token()
    if not access_token:
        logging.error("Failed to authenticate with GitHub.")
        return "Authentication failed", 500

    owner = session.get('github_username')

    branches = get_branches(owner=owner, repo_name=repo_name)
    
    if branches is not None:
        logging.info(f"Branches for repository '{repo_name}': {', '.join(branches)}")
        
        return render_template('repo_details.html',owner=owner, branches=branches, repo_name=repo_name)
    else:
        logging.error(f"Failed to fetch branches for repository '{repo_name}'.")
        return "Failed to fetch branches", 500

@main_routes.route('/repositories/<repo_name>/issues', methods=['GET', 'POST'])
def manage_issues(repo_name):
    """
    Displays and manages issues for a specific repository. Allows viewing and creating or closing issues
    """
    if not is_user_logged_in():
        logging.warning("User attempted to access issues without being logged in.")
        return "You are not logged in", 403

    if request.method == 'GET':
        # Fetch and display issues
        issues = get_github_issues(repo_name)
        if issues is not None:
            logging.info(f"Fetched {len(issues)} issues for repository: {repo_name}")
            return render_template('issues.html', repo_name=repo_name, issues=issues)
        else:
            logging.error(f"Failed to fetch issues for repository: {repo_name}")
            return "Failed to fetch issues from GitHub", 500

    elif request.method == 'POST':
        if request.form.get('action') == 'close':
            # Close an existing issue
            issue_number = request.form.get('issue_number')
            if not issue_number:
                return "Issue number is required", 400
            closed_issue = close_github_issue(repo_name, issue_number)
            if closed_issue:
                logging.info(f"Issue #{issue_number} successfully closed in repository {repo_name}.")
                return redirect(url_for('main.manage_issues', repo_name=repo_name))
            else:
                return "Failed to close the issue", 500

        else:
            # Create a new issue
            title = request.form.get('title')
            body = request.form.get('body')
            if not title:
                return "Issue title is required", 400
            new_issue = create_github_issue(repo_name, title, body)
            if new_issue:
                logging.info(f"Issue created successfully in repository {repo_name}.")
                return redirect(url_for('main.manage_issues', repo_name=repo_name))

@main_routes.route('/delete_repo', methods=['GET', 'POST'])
def delete_repositories():
    """
    Displays repositories and allows deletion of selected ones.
    """
    if not is_user_logged_in():
        logging.warning("Unauthorized access to delete repositories.")
        return "You are not logged in", 403

    if request.method == 'GET':
        # Fetch and display repositories
        repositories = get_github_repositories(session.get('github_username'), get_installation_access_token())
        if repositories:
            return render_template('delete_repo.html', repositories=repositories)
        else:
            return "Failed to fetch repositories", 500

    elif request.method == 'POST':
        # Delete selected repositories
        repos_to_delete = request.form.getlist('repo_to_delete[]')
        if not repos_to_delete:
            return "No repositories selected for deletion", 400

        result_message = delete_repository(repos_to_delete)
        logging.info(result_message)
        flash(result_message) 
        return redirect(url_for('main.delete_repositories'))

@main_routes.route('/repositories/<repo_name>/pull_requests', methods=['GET', 'POST'])
def manage_pull_requests(repo_name):
    """
    Handles pull requests for a repository:
    - GET: Lists all pull requests, fetches details of a specific pull request, or renders the create form if `create` is requested.
    - POST: Allows creating or merging pull requests.
    """
    if not is_user_logged_in():
        logging.warning("User attempted to access pull requests without being logged in.")
        return "You are not logged in", 403

    access_token = get_installation_access_token()
    if not access_token:
        logging.error("Failed to get access token for managing pull requests.")
        return "Failed to authenticate with GitHub", 500

    if request.method == 'GET':
        # Check if a specific pull request is requested
        pr_number = request.args.get('pr_number')
        create_form = request.args.get('create')

        if pr_number:
            # Fetch details of the specific pull request
            pull_request = view_pull_request(session.get('github_username'), repo_name=repo_name, pr_number=int(pr_number))
            if pull_request:
                logging.info(f"Fetched details for pull request #{pr_number} in repository: {repo_name}")
                return render_template('pull_request_details.html', pull_request=pull_request, repo_name=repo_name)
            else:
                logging.error(f"Failed to fetch details for pull request #{pr_number} in repository: {repo_name}")
                return f"Failed to fetch details for pull request #{pr_number}", 500

        elif create_form:
            # Fetch branches and render the form for creating a pull request
            branches = get_branches(session.get('github_username'), repo_name=repo_name)  
            if branches is None:
                logging.error(f"Failed to fetch branches for repository {repo_name}.")
                return "Failed to fetch branches from GitHub", 500

            logging.info(f"Fetched {len(branches)} branches for repository: {repo_name}")
            return render_template('create_pull_request.html', repo_name=repo_name, branches=branches)

        else:
            # Fetch and display all pull requests
            pull_requests = get_pull_requests(session.get('github_username'), repo_name=repo_name)
            if pull_requests is not None:
                logging.info(f"Fetched {len(pull_requests)} pull requests for repository: {repo_name}")

app/templates/contents.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Repository Contents</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <!-- Repository and Branch Information -->
        <h1 class="mb-4">Repository Contents</h1>
        <h4 class="text-muted">{{ repo }}</h4>
        <div class="d-flex align-items-center mb-4">
            <span class="me-2">Current Branch:</span>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="branchDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                    {{ current_branch }}
                </button>
                <ul class="dropdown-menu" aria-labelledby="branchDropdown">
                    {% for branch in branches %}
                        <li>
                            <a class="dropdown-item" href="{{ url_for('main.get_contents', owner=owner, repo=repo, branch=branch.name) }}">
                                {{ branch.name }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <!-- Back to Home Button -->
        <a href="{{ url_for('main.home') }}" class="btn btn-secondary mb-4">Back to Home</a>

        <!-- Repository Contents -->
        {% if contents %}
            <ul class="list-group">
                {% for item in contents %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <div>
                            <strong>{{ item.name }}</strong> 
                            {% if item.type == 'dir' %}
                                <span class="badge bg-primary ms-2">Directory</span>
                            {% else %}
                                <span class="badge bg-success ms-2">File</span>
                            {% endif %}
                        </div>
                        <div>
                            {% if item.type == 'dir' %}
                                <a href="{{ url_for('main.get_contents', owner=owner, repo=repo, path=item.path, branch=current_branch) }}" class="btn btn-outline-info btn-sm">View</a>
                            {% else %}
                                <a href="{{ item.download_url }}" class="btn btn-outline-secondary btn-sm" target="_blank">Download</a>
                                <a href="#" class="btn btn-outline-warning btn-sm" data-bs-toggle="modal" data-bs-target="#updateFileModal" 
                                   data-path="{{ item.path }}" data-sha="{{ item.sha }}">Edit</a>
                                <form action="{{ url_for('main.delete_existing_file', owner=owner, repo=repo, path=item.path) }}" method="POST" class="d-inline">
                                    <input type="hidden" name="sha" value="{{ item.sha }}">
                                    <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                                </form>
                            {% endif %}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p class="text-warning">No contents available for this repository.</p>
        {% endif %}

        <!-- Issues Section -->
        <h3 class="mt-5">Issues</h3>
        {% if issues %}
            <ul class="list-group">
                {% for issue in issues %}
                    <li class="list-group-item">
                        <strong>#{{ issue.number }}:</strong> {{ issue.title }}
                        <span class="badge bg-{{ 'success' if issue.state == 'closed' else 'warning' }} ms-2">{{ issue.state }}</span>
                        <div class="float-end">
                            <!-- Button to view issue in your app -->
                            <a href="{{ url_for('main.manage_issues', repo_name=repo, issue_number=issue.number) }}" class="btn btn-outline-info btn-sm me-2">View in App</a>
                            <!-- Button to view issue on GitHub -->
                            <a href="{{ issue.html_url }}" class="btn btn-outline-secondary btn-sm" target="_blank">View on GitHub</a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p class="text-warning">No issues available for this repository.</p>
        {% endif %}

        <!-- Pull Requests Section -->
        <h3 class="mt-5">Pull Requests</h3>
        {% if pull_requests %}
            <ul class="list-group">
                {% for pr in pull_requests %}
                    <li class="list-group-item">
                        <strong>#{{ pr.number }}:</strong> {{ pr.title }}
                        <span class="badge bg-{{ 'success' if pr.state == 'closed' else 'primary' }} ms-2">{{ pr.state }}</span>
                        <div class="float-end">
                            <!-- Button to view pull request in your app -->
                            <a href="{{ url_for('main.manage_pull_requests', repo_name=repo, pr_number=pr.number) }}" class="btn btn-outline-info btn-sm me-2">View in App</a>
                            <!-- Button to view pull request on GitHub -->
                            <a href="{{ pr.html_url }}" class="btn btn-outline-secondary btn-sm" target="_blank">View on GitHub</a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p class="text-warning">No pull requests available for this repository.</p>
        {% endif %}

        <!-- Add File Modal -->
        <button class="btn btn-primary mt-4" data-bs-toggle="modal" data-bs-target="#addFileModal">Add New File</button>
        <div class="modal fade" id="addFileModal" tabindex="-1" aria-labelledby="addFileModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form action="{{ url_for('main.create_new_file', owner=owner, repo=repo) }}" method="POST">
                        <div class="modal-header">
                            <h5 class="modal-title" id="addFileModalLabel">Add New File</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <div class="mb-3">
                                <label for="fileName" class="form-label">File Name</label>
                                <input type="text" class="form-control" id="fileName" name="path" placeholder="e.g tgkcapture.txt" required>
                            </div>
                            <div class="mb-3">
                                <label for="fileContent" class="form-label">File Content</label>
                                <textarea class="form-control" id="fileContent" name="content" rows="5" required></textarea>
                            </div>
                            <div class="mb-3">
                                <label for="commitMessage" class="form-label">Commit Message</label>
                                <input type="text" class="form-control" id="commitMessage" name="message" placeholder="Add a meaningful message" required>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Create File</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- Update File Modal -->
        <div class="modal fade" id="updateFileModal" tabindex="-1" aria-labelledby="updateFileModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form action="{{ url_for('main.update_existing_file', owner=owner, repo=repo, path='') }}" 
                        method="POST"
                        onsubmit="this.action = this.action.replace('path=', 'path=' + encodeURIComponent(document.getElementById('updateFilePath').value))">
                        <div class="modal-header">
                            <h5 class="modal-title" id="updateFileModalLabel">Update File</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <input type="hidden" id="updateFilePath" name="path">
                            <input type="hidden" id="updateFileSha" name="sha">
                            <div class="mb-3">
                                <label for="updateFileContent" class="form-label">File Content</label>
                                <textarea class="form-control" id="updateFileContent" name="content" rows="5" required></textarea>
                            </div>
                            <div class="mb-3">
                                <label for="updateCommitMessage" class="form-label">Commit Message</label>
                                <input type="text" class="form-control" id="updateCommitMessage" name="message" placeholder="Add a meaningful message" required>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-warning">Update File</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const updateFileModal = document.getElementById('updateFileModal');
            updateFileModal.addEventListener('show.bs.modal', (event) => {
                const button = event.relatedTarget;
                const path = button.getAttribute('data-path');
                const sha = button.getAttribute('data-sha');
                document.getElementById('updateFilePath').value = path;
                document.getElementById('updateFileSha').value = sha;
                console.log(`Path set in modal: ${path}`);
            });
        });
    </script>
</body>
</html>

app/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error | RepoMaster</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/error.css') }}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body>
    <div class="w3-display-middle">
    <h1 class="w3-jumbo w3-animate-top w3-center"><code>Access Denied</code></h1>
    <hr class="w3-border-white w3-animate-left" style="margin:auto;width:50%">
    <h3 class="w3-center w3-animate-right">{{ error_message }}</h3>
    <h3 class="w3-center w3-animate-zoom">🚫🚫🚫🚫</h3>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome | RepoMaster</title>
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Raleway" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
    
</head>
<body>

    <header>
        <h2><a href="#">RepoMaster</a></h2>
        <nav>
            <li><a href="#hero">Home</a></li>
            <li><a href="#services">Services</a></li>
            {% if is_user_logged_in() %}
                <li><a href="{{ url_for('main.show_github_repositories') }}">View Repositories</a></li>
                <li><a href="{{ url_for('main.logout') }}">Log Out</a></li>
                
                <!-- Profile section -->
                <li class="profile-container">
                    <img src="{{ session.get('github_avatar_url') }}" alt="GitHub Profile" class="profile-pic">
                    <span class="profile-username">{{ session.get('github_username') }}</span>
                </li>
            {% else %}
                <li><a href="{{ url_for('main.install_github_app') }}">Login with GitHub</a></li>
            {% endif %}
        </nav>
    </header>
    
    
    <section class="hero" id="hero">
        <div class="background-image"></div>
        <div class="hero-content-area">
        <h1>RepoMaster!</h1>
        <h3>Master Your Repositories with RepoMaster</h3>
        <a href="" class="btn">Get Started</a>
        </div>
    </section>
        
    <section class="services" id="services">
        <h3 class="title">What Our Service Offers</h3>
        <p>RepoMaster offers a comprehensive suite of services designed to streamline your GitHub repository management experience. From effortlessly deleting multiple repositories to gaining insights into all issues across your projects, our platform empowers you to take control of your GitHub workflow. Explore our range of services below to discover how RepoMaster can simplify your repository management tasks and enhance your productivity.</p>
        <hr>
    
        <ul class="grid">
        <li>
            <i class="fa-solid fa-code-pull-request fa-4x"></i>
            <h4>Pull Requests</h4>
            <p>PRs.</p>
        </li>
        <li>
            <i class="fa-solid fa-code-commit fa-4x"></i>
            <h4>Commits</h4>
            <p>Commits.</p>
        </li>
        <li>
            <i class="fa-solid fa-code-fork fa-4x"></i>
            <h4>Fork</h4>
            <p>Forks</p>
        </li>
        <li>
            <i class="fa-brands fa-git-alt fa-4x"></i>
            <h4>git</h4>
            <p>git</p>
        </li>
        </ul>
    </section>
    
    <footer>
        <p>RepoMaster</p>
        <p>Made With ❤️ by Grant Corp</p>
        <ul>
        <li><a href="#"><i class="fa fa-twitter-square fa-2x"></i></a></li>
        <li><a href="#"><i class="fa fa-facebook-square fa-2x"></i></a></li>
        <li><a href="#"><i class="fa fa-snapchat-square fa-2x"></i></a></li>
        </ul>
    </footer>

    
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>

</body>
</html>